version: 2

updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: "/frontend/admin-web"
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: "/frontend/public-web"
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: "/services/hotel-service"
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: "/services/booking-service"
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: "/services/identity-service"
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: "/services/notification-service"
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: "/services/api-gateway"
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: "/frontend/admin-web"
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: "/frontend/public-web"
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
