create table identity_roles (
    id bigint generated by default as identity primary key,
    name varchar(100) not null unique
);

create table identity_users (
    id bigint generated by default as identity primary key,
    username varchar(150) not null unique,
    password varchar(255) not null,
    enabled boolean not null
);

create table identity_user_roles (
    user_id bigint not null,
    role_id bigint not null,
    primary key (user_id, role_id),
    constraint fk_identity_user_roles_user
        foreign key (user_id) references identity_users(id),
    constraint fk_identity_user_roles_role
        foreign key (role_id) references identity_roles(id)
);

create table identity_user_hotels (
    user_id bigint not null,
    hotel_id uuid not null,
    primary key (user_id, hotel_id),
    constraint fk_identity_user_hotels_user
        foreign key (user_id) references identity_users(id)
);

create table identity_role_permissions (
    role_id bigint not null,
    permissions varchar(100) not null,
    primary key (role_id, permissions),
    constraint fk_identity_role_permissions_role
        foreign key (role_id) references identity_roles(id)
);
