spring:
  datasource:
    url: ${BOOKING_DB_URL:jdbc:postgresql://localhost:5432/booking_service}
    username: ${BOOKING_DB_USERNAME:hotel_booking}
    password: ${BOOKING_DB_PASSWORD:hotel_booking_dev_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
